services:
  backend:
    container_name: backend
    build:
      context: .
      target: ${NODE_ENV}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${APPLICATION_PORT}:3000
    env_file:
      - .env
    networks:
      - webnet

networks:
  webnet:
