services:
  backend:
    command: npm run start:debug
    ports:
      - 127.0.0.1:9229:9229

  data-microservice:
    command: npm run start:debug
    ports:
      - 127.0.0.1:9230:9229
      - 127.0.0.1:81:3000

  redis:
    ports:
      - '127.0.0.1:6379:6379'

  redisinsight:
    container_name: redisinsight
    image: 'redislabs/redisinsight:latest'
    restart: always
    depends_on:
      - redis
    ports:
      - '127.0.0.1:8001:8001'
    # volumes:
    #   - cache:/data
