services:
  backend:
    container_name: backend
    build:
      context: backend/.
      target: ${NODE_ENV}
    volumes:
      - ./backend/.:/usr/src/app
      - ./backend/node_modules:/usr/src/app/node_modules
    # ports:
    #   - 127.0.0.1:${APPLICATION_PORT}:3000
    env_file:
      - .env
    depends_on:
      - data-microservice

  data-microservice:
    container_name: data-microservice
    build:
      context: data-microservice/.
      target: ${NODE_ENV}
    volumes:
      - ./data-microservice/.:/usr/src/app
      - ./data-microservice/node_modules:/usr/src/app/node_modules
    # ports:
    #   - 127.0.0.1:${APPLICATION_PORT}:3000
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    container_name: redis
    image: 'redis:7-alpine'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS}
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - cache:/data

  nginx:
    container_name: nginx
    build:
      context: docker/nginx/.
      target: nginx
    depends_on:
      - backend
    restart: always
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host

volumes:
  cache:
    driver: local
